import '@/styles/globals.css';
import type { AppProps } from 'next/app';

// pages/_app.js
import { chakraTheme } from '@/styles/chakra-theme';
import { ChakraProvider } from '@chakra-ui/react';
import {
  ArcElement,
  BarElement,
  CategoryScale,
  Chart as ChartJS,
  Colors,
  Legend,
  LineElement,
  LinearScale,
  PointElement,
  ScatterController,
  RadarController,
  RadialLinearScale,
  Title,
  Filler,
  Tooltip,
} from 'chart.js';
import Head from 'next/head';

ChartJS.register(
  CategoryScale,
  LinearScale,
  RadialLinearScale,
  ArcElement,
  PointElement,
  LineElement,
  BarElement,
  ScatterController,
  RadarController,
  Title,
  Tooltip,
  Legend,
  Colors,
  Filler
);

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider theme={chakraTheme}>
      <Head>
        <title>Tweek Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Component {...pageProps} />
    </ChakraProvider>
  );
}

export default MyApp;
